apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: block-ingress-egress-test
spec:
  podSelector:
    matchLabels:
      k8s-app: coredns
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - ports:
    - protocol: TCP
      port: 53
  egress:
  - ports:
    - protocol: TCP
      port: 80
      
